package com.suyash.demo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class JpaApplication {

	public static void main(String[] args) {
		SpringApplication.run(JpaApplication.class, args);
	}

}
// Q. WHY TO USE DOCKER :
//LET TAKE AN EG :MULTIPLE DEVELOPERS ARE WORK ONE PROJECT, LETS SUPPOSE ONE DEV USES THE VERSION JAVA 17, AND 2ND DEVELOPER USING JAVA VERSION 22.
// WHEN DEV 1 PUSH THE PROJECT ON SHARING ENVIRONMENT AND DEV 2 PULLS THE SHARES REQUEST, BECAUSE OF DIFFERENT JAVA VERSION IT GIVES OR SHOOT MANUAL ERROR TO OVERCOME FROM THESE WE USE DOCKER.

//WHAT IS DOCKER: 1. DOCKER IS A PLATFORM, HELPS TO CREATE THE CONTAINER.WHICH CONTAINS THE CODE, RUNTIME LIBRARIES, SYSTEM TOOLS, DEPENDENCY AND PROVIDE IT AS AN SINGLE UNIT PACKAGE,DUE TO IT WEE NOT NEED TO INSTALL DEPENDENCY MULTIPLE TIMES AND WE COME OVER  FROM THE MANUAL ERROR PRODUCE BY IT


//WHAT IS DOCKER IMAGE:

//What is PostgresSql in object-relational database management system (ORDBMS)
//:-
